
services:
  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pavan@2004
      MYSQL_DATABASE: bankingdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  bank-app:
    build: .
    container_name: bank-app
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankingdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pavan@2004
      SERVER_PORT: 8081

volumes:
  mysql-data:
