services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankingdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pavan@2004

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Pavan@2004
      MYSQL_DATABASE: bankingdb
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
